version: "3"
services:

  db_ms_cadcolaborador:
    image: 'mysql'
    container_name: db_ms_cadcolaborador
    environment:
      - 'MYSQL_DATABASE=ms_cadcolaborador_db'
      - 'MYSQL_PASSWORD=mh8q23pr99'
      - 'MYSQL_ROOT_PASSWORD=mh8q23pr99'
      - 'MYSQL_USER=admin'
    ports:
      - 3306:3306
    volumes:
      - vol_cadcolaborador_db:/db/ms_cadcolaborador_db


  ms_cadcolaborador:
    build: /Cad_Funcionario/App
    container_name: ms_cadcolaborador
    ports:
      - 8092:8092
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://ms_cadcolaborador_db:3306/ms_cadcolaborador_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=mh8q23pr99
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring.servlet.multipart.max-file-size=350MB
      - spring.servlet.multipart.max-request-size=350MB
      - app.caminhoImagem=/app/
      - app.caminhoImagemZip=/app/Zip/
    depends_on:
      - ms_cadcolaborador_db
    restart: on-failure
    volumes:
      - file:/app/
      - filezip:/app/Zip/


volumes:
  file:
  filezip:
  vol_cadcolaborador_db: